[package]
name = "fuel-core-chain-config"
version = { workspace = true }
authors = { workspace = true }
categories = ["cryptography::cryptocurrencies"]
edition = { workspace = true }
homepage = { workspace = true }
keywords = ["blockchain", "cryptocurrencies", "fuel-client"]
license = { workspace = true }
repository = { workspace = true }
description = "Fuel Chain config types"

[dependencies]
impl-tools = { workspace = true }
anyhow = { workspace = true }
bech32 = { version = "0.9.0", default-features = false }
fuel-core-storage = { workspace = true }
fuel-core-types = { workspace = true, default-features = false, features = [
  "serde",
] }
hex = { version = "0.4", features = ["serde"] }
itertools = { workspace = true, features = ["use_alloc"] }
parquet = { workspace = true, features = ["zstd"], optional = true }
postcard = { version = "1.0", features = ["alloc"] }
rand = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive", "rc"] }
serde_json = { version = "1.0", features = ["raw_value"], optional = true }
serde_with = "1.11"
tracing = { version = "0.1", default-features = false }

[dev-dependencies]
test-case = { workspace = true }
insta = { workspace = true }
fuel-core-chain-config = { path = ".", features = ["parquet"] }
strum = { workspace = true, features = ["derive"] }
bytes = { workspace = true }
fuel-core-types = { workspace = true, default-features = false, features = [
  "random",
  "serde",
] }
pretty_assertions = { workspace = true }
rand = { workspace = true }
serde_json = { version = "1.0", features = ["raw_value"] }
tempfile = { workspace = true }

[features]


std = [
  "itertools/use_std",
  "serde_json/std",
  "fuel-core-types/std",
  "anyhow/std",
  "tracing/std",
  "bech32/std",
]
default = ["std", "random"]
parquet = ["std", "dep:parquet", "postcard/use-std"]
random = ["dep:rand", "fuel-core-types/random"]
